board/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
from .views import SaleViewSet, BidViewSet

app_name = 'board'

router = routers.DefaultRouter()
router.register(r'sale_api', SaleViewSet)
router.register(r'bid_api', BidViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.index, name='index'),
    path('<int:sale_id>/', views.detail, name='detail'),
    path('bid/create/<int:sale_id>/', views.bid_create, name='bid_create'),
    path('sale/create/', views.sale_create, name='sale_create'),
    path('sale/modify/<int:sale_id>/', views.sale_modify, name='sale_modify'),
    path('sale/delete/<int:sale_id>/', views.sale_delete, name='sale_delete'),
    path('bid/accept/<int:bid_id>/', views.bid_accept, name='bid_accept'),
]

common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from rest_framework import routers
from .views import UserViewSet

app_name = 'common'

router = routers.DefaultRouter()
router.register(r'user', UserViewSet)

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('', include(router.urls)),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include('board.urls')),
    path("common/", include('common.urls')),
    path("", views.index, name='index'),
]

board/models.py
from django.db import models
#from django.contrib.auth.models import User
from common.models import User


# Create your models here.
class Sale(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.CharField(max_length=50)
    description = models.TextField()
    price = models.PositiveIntegerField()
    sold = models.BooleanField(default=False)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.product


class Bid(models.Model):
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    content = models.TextField()
    agreed = models.IntegerField(default=0)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

common/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    broker_id = models.CharField(max_length=30, blank=True, unique=True)

board/forms.py
from django import forms
from .models import Sale, Bid


class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale  # 사용할 모델
        fields = ['product', 'description', 'price']
        labels = {
            'product': 'Product Name',
            'price': 'Price',
            'description': 'Description',
        }


class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['content']
        labels = {
            'content': 'Comment',
        }

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
#from django.contrib.auth.models import User
from .models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="Email")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email", "broker_id")

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Sale, Bid
from .forms import SaleForm, BidForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from rest_framework import viewsets
from .serializers import SaleSerializer, BidSerializer
from django_filters.rest_framework import DjangoFilterBackend

class SaleViewSet(viewsets.ModelViewSet):
    queryset = Sale.objects.all()
    serializer_class = SaleSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['id']



class BidViewSet(viewsets.ModelViewSet):
    queryset = Bid.objects.all()
    serializer_class = BidSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['buyer_id', 'agreed']


def index(request):
    page = request.GET.get('page', '1')
    sale_list = Sale.objects.order_by('-create_date')
    paginator = Paginator(sale_list, 10)
    page_obj = paginator.get_page(page)
    context = {'sale_list': page_obj}
    return render(request, 'board/sale_list.html', context)


def detail(request, sale_id):
    sale = get_object_or_404(Sale, pk=sale_id)
    context = {'sale': sale}
    return render(request, 'board/sale_detail.html', context)


@login_required(login_url='common:login')
def bid_create(request, sale_id):
    sale = get_object_or_404(Sale, pk=sale_id)
    if request.method == "POST":
        form = BidForm(request.POST)
        if form.is_valid():
            bid = form.save(commit=False)
            bid.buyer = request.user
            bid.create_date = timezone.now()
            bid.sale = sale
            bid.save()
            return redirect('board:detail', sale_id=sale.id)
    else:
        form = BidForm()
    context = {'sale': sale, 'form': form}
    return render(request, 'board/sale_detail.html', context)


@login_required(login_url='common:login')
def sale_create(request):
    if request.method == 'POST':
        form = SaleForm(request.POST)
        if form.is_valid():
            sale = form.save(commit=False)
            sale.seller = request.user
            sale.create_date = timezone.now()
            sale.save()
            return redirect('board:index')
    else:
        form = SaleForm()
    context = {'form': form}
    return render(request, 'board/sale_form.html', context)


@login_required(login_url='common:login')
def sale_modify(request, sale_id):
    sale = get_object_or_404(Sale, pk=sale_id)
    if request.user != sale.seller:
        messages.error(request, 'You have no right to Modify')
        return redirect('board:detail', sale_id=sale.id)
    if request.method == "POST":
        form = SaleForm(request.POST, instance=sale)
        if form.is_valid():
            sale = form.save(commit=False)
            sale.modify_date = timezone.now()
            sale.save()
            return redirect('board:detail', sale_id=sale.id)
    else:
        form = SaleForm(instance=sale)
    context = {'form': form}
    return render(request, 'board/sale_form.html', context)


@login_required(login_url='common:login')
def sale_delete(request, sale_id):
    sale = get_object_or_404(Sale, pk=sale_id)
    if request.user != sale.seller:
        messages.error(request, 'You have no right to delete it.')
        return redirect('board:detail', sale_id=sale.id)
    sale.delete()
    return redirect('board:index')


@login_required(login_url='common:login')
def bid_accept(request, bid_id):
    bid = get_object_or_404(Bid, pk=bid_id)
    if request.user != bid.sale.seller:
        messages.error(request, 'Only Seller can accept the trade request')
        return redirect('board:detail', sale_id=bid.sale.id)
    if not bid.agreed and not bid.sale.sold:
        bid.agreed = True
        bid.sale.sold = True
        bid.save()
        bid.sale.save()
        return redirect('board:detail', sale_id=bid.sale.id)
    else:
        messages.error(request, 'You already accepted the trade request')
        return redirect('board:detail', sale_id=bid.sale.id)

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm
from rest_framework import viewsets
from .serializers import UserSerializer
from .models import User
from django_filters.rest_framework import DjangoFilterBackend

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['username', 'broker_id']

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- board CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Secondhand Goods Trade</title>
</head>
<body>
{% include "navbar.html" %}
<!-- Template Start -->
{% block content %}
{% endblock %}
<!-- Template End -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- JavaScript Start -->
{% block script %}
{% endblock %}
<!-- JavaScript End -->
</body>
</html>

templates/board/sale_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- Product -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ sale.product }}</h2>
    {% if sale.sold %}
        <div class="badge bg-warning">Sold Out</div>
    {% else %}
        <div class="badge bg-primary">For Sale</div>
    {% endif %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ sale.description }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ sale.seller.username }}</div>
                    <div>{{ sale.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
            {% if request.user == sale.seller %}
            <a href="{% url 'board:sale_modify' sale.id  %}"
                class="btn btn-sm btn-outline-secondary">Modify</a>
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                data-uri="{% url 'board:sale_delete' sale.id  %}">Delete</a>
            {% endif %}
            </div>
        </div>
    </div>
    <!-- bid -->
    <h5 class="border-bottom my-3 py-2">Currently, {{sale.bid_set.count}} offers exist</h5>
    {% for bid in sale.bid_set.all %}
    <div class="card my-3">
        <div class="card-body">
            {% if bid.agreed %}
                <div class="badge bg-success">Accepted</div>
                {% if request.user == bid.buyer %}
                    <br>
                    <div class="badge bg-success">Seller's Broker ID : {{ sale.seller.broker_id }}</div>
                {% elif request.user == sale.seller %}
                    <br>
                    <div class="badge bg-success">Buyer's Broker ID : {{ bid.buyer.broker_id }}</div>
                {% endif %}
            {% endif %}
            <div class="card-text" style="white-space: pre-line;">{{ bid.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ bid.buyer.username }}</div>
                    <div>{{ bid.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == sale.seller and not sale.sold %}
                <a href="{% url 'board:bid_accept' bid.id  %}"
                   class="btn btn-sm btn-outline-secondary">Accept</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    {% if request.user != sale.seller and not sale.sold%}
        <!-- make bid -->
        <form action="{% url 'board:bid_create' sale.id %}" method="post" class="my-3">
            {% csrf_token %}
            <!-- 오류표시 Start -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="mb-3">
                <label for="content" class="form-label">Make an Offer</label>
                <textarea {% if not user.is_authenticated %}disabled{% endif %}
                          name="content" id="content" class="form-control" rows="10"></textarea>
            </div>
            <input type="submit" value="Make a Deal" class="btn btn-primary">
        </form>
    {% endif %}
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("Are you sure you want to delete it?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/board/sale_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Upload your Goods for Sale</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="product" class="form-label">Product Name</label>
            <input type="text" class="form-control" name="product" id="product"
                   value="{{ form.product.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="number" min="0" max="3000000" class="form-control" name="price"
                      id="price" value="{{ form.price.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea class="form-control" name="description"
                      id="description" rows="10">{{ form.description.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
</div>
{% endblock %}

templates/board/sale_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th class="text-center" style="width:15%">Number</th>
            <th class="text-center" style="width:30%">Product</th>
            <th class="text-center" style="width:10%">Status</th>
            <th class="text-center" style="width:25%">Seller</th>
            <th class="text-center" style="width:20%">Date</th>
        </tr>
        </thead>
        <tbody>
        {% if sale_list %}
        {% for sale in sale_list %}
        <tr class="text-center">
            <td>{{ sale_list.paginator.count|sub:sale_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td class="text-center">
                <a href="{% url 'board:detail' sale.id %}">{{ sale.product }}</a>
                {% if sale.bid_set.count > 0 %}
                <span class="text-danger small mx-2">{{ sale.bid_set.count }}</span>
                {% endif %}
            </td>
            {% if sale.sold %}
                <td><div class="badge bg-warning">Sold Out</div></td>
            {% else %}
                <td><div class="badge bg-primary">For Sale</div></td>
            {% endif %}
            <td>{{ sale.seller.username }}</td>
            <td>{{ sale.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="5">No Goods on Sale</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- Paging Start -->
    <ul class="pagination justify-content-center">
        <!-- Prev -->
        {% if sale_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ sale_list.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Previous</a>
        </li>
        {% endif %}
        <!-- Pagelist -->
        {% for page_number in sale_list.paginator.page_range %}
        {% if page_number >= sale_list.number|add:-5 and page_number <= sale_list.number|add:5 %}
        {% if page_number == sale_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- next_page -->
        {% if sale_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ sale_list.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
    <!-- Paging Ends -->
    <a href="{% url 'board:sale_create' %}" class="btn btn-primary">Upload your Goods for Sale</a>
</div>
{% endblock %}

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">User ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">User ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">Password</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">Password Verification</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">E-Mail</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="broker_id">Broker ID</label>
            <input type="text" class="form-control" name="broker_id" id="broker_id"
                   value="{{ form.broker_id.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">Create Account</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
<!-- error print -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- field error -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- non_field error -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'board:index' %}">Secondhand Forum</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (Logout)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">Login</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">Sign Up</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>